# permissions for end users to edit middlewareclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: middlewarecluster-editor-role
rules:
- apiGroups:
  - apps.devless.toplogy.com
  resources:
  - middlewareclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.devless.toplogy.com
  resources:
  - middlewareclusters/status
  verbs:
  - get
